image: node:latest

cache:
  paths:
    - node_modules/

deploy:
  stage: deploy
  environment: Production
  only:
    - master
  script:
    - npm install -g firebase-tools
    - yarn install
    - yarn build
    - firebase deploy --non-interactive --token $FIREBASE_TOKEN
